services:
  postgres:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  library:
    container_name: library_app
    image: library:latest
    build:
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/library
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_LIQUIBASE_ENABLED: true
    depends_on:
      - postgres
    networks:
        - app-network
    ports:
        - 8080:8080

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: